### PR TITLE
Completed alignment and reconstruction page

### PR DESCRIPTION
**Pull request by zhuokaizhao**

### CODE REVIEW

**Comment by cryos** [comment]
I don't understand why you would delete viz.md, this branch has conflicts with master. I think you need to correctly start your branch from master after the viz branch was merged, it looks like you did not do that. If you are unsure of how to create new topic branches from updated master @cjh1 can help you - I am out on travel this week.

**Comment by zhuokaizhao** [comment]
Sorry, I just solved the conflict.

**Comment by cjh1** [comment]
This is looking good, I am seeing one strange thing, the font color for 'Data As', see below:

screen

Any idea what is going on here?

**Comment by zhuokaizhao** [comment]
> This is looking good, I am seeing one strange thing, the font color for 'Data As', see screenshot below:
> 
> screen
> 
> Any idea what is going on here?

I was not sure the reason - probably there is some kinds of recognition that was used inside MkDocs, as I found their tutorial page also had this colour issue. 

Instead of quoting using markdown style, I changed them to HTML's <code></code>. There shouldn't be any more strange-colour fonts.

**Pull request merged**
